context('convert functions')

library(data.table)

test_that('convert RCMIP helper functions', {
  
  # Test specifc emission species, that have had conversion issues in the past.
  x <- 10 
  
  n2o_entry <- data.table::as.data.table(hectordata::rcmipCMIP6_conversion)[hector_variable == "N2O_emissions", ]
  ztrue <- x * (biogas::molMass("N2O") / (biogas::molMass("N") * 2))
  # Divide by 100 to force back to arbitrary units 
  z     <- ud_convert2(x, from = n2o_entry$hector_udunits, to = n2o_entry$rcmip_udunits)/1000
  testthat::expect_equal(z, ztrue)
  

  so2_entry <-   data.table::as.data.table(hectordata::rcmipCMIP6_conversion)[hector_variable == "SO2_emissions", ]
  ztrue <- x * (biogas::molMass("S") / biogas::molMass("SO2"))
  z     <- ud_convert2(x, from = so2_entry$rcmip_udunits, to = so2_entry$hector_udunits)/1000

})



test_that('RCMIP generated tables match old rcp time series', {
  
  new_rcp45 <- convert_rcp_hector(scenario = "rcp45", years = 1700:2100)
  names(new_rcp45) <- c("scenario", "Date", "variable", "units", "new_value")
  
  # The RCP 45 input table that was used historiaclly, to compare with the result 
  # produced by the RCMIP conversion pipeline. 
  original_inputs <- read.csv("comparison_RCP45_emiss.csv", comment.char = ";")
  as.data.table(original_inputs) %>% 
    melt(id.vars = "Date", value.name = "old_value") -> 
    long_original_data
  
  # Combine the old and new data ito a single data frame. Compare the values with one 
  # another, the values of the converted emission values should be the same, we would 
  # expect the percent difference between the values to be small. 
  comparison_df <- long_original_data[new_rcp45, on = c("variable", "Date"), all = TRUE] 
  
  # The percent difference between the two RCP inputs should be small. 
  data <- na.omit(comparison_df)
  data[ , percent_change :=  100 * (new_value - old_value) / old_value]
  mean_difference   <- data[ Date %in% 1850:2100, .(avg = mean(percent_change, na.rm = TRUE)), by = variable]
  trivial_threshold <- 0.5 # the average percent difference should be less than half of a percent different.
  testthat::expect_true(all(abs(mean_difference$avg) < trivial_threshold))
  
  # Note that the input tables generated by the hectordata & the older input tables is that 
  # the input tables also include values for the constraints & NH3 emissions. So all of the 
  # NA values in the comparison data frame should correspond to a constraint entry or the NH3 emissions.
  no_old_values <- unique(comparison_df[is.na(old_value),][["variable"]])
  expected_pattern <- "_constrain|NH3_emissions"
  testthat::expect_true(all(grepl(pattern = expected_pattern, x = no_old_values)))
  
})