
# Test to make sure that the rcmip conversion is being done correctly by comparing the contents of the
# RCP 45 rcmip generated file with the values from the pre hectordata times. 
test_that('rcmip conversion', {
  
  # Read in the new rcp emissions from the package. 
  new_rcp45 <- read.csv(file.path(TABLES_DIR, "rcmip_rcp45_emiss-constraints_rf.csv"), comment.char = ";", stringsAsFactors = FALSE)
  suppressWarnings({
    as.data.table(new_rcp45) %>% 
      melt(id.vars = "Date", value.name = "new_value") -> 
      new_rcp45
  })

  # The RCP 45 input table that was used historiaclly, to compare with the result 
  # produced by the RCMIP conversion pipeline. 
  original_inputs <- read.csv("./comp_data/comparison_RCP45_emissions.csv", comment.char = ";")
  as.data.table(original_inputs) %>% 
    melt(id.vars = "Date", value.name = "old_value") -> 
    long_original_data
  
  # Combine the old and new data ito a single data frame. Compare the values with one 
  # another, the values of the converted emission values should be the same, we would 
  # expect the percent difference between the values to be small. 
  comparison_df <- long_original_data[new_rcp45, on = c("variable", "Date"), all = TRUE] 
  
  # The percent difference between the two RCP inputs should be small. 
  data <- na.omit(comparison_df)
  data[ , percent_change :=  100 * (new_value - old_value) / old_value]
  mean_difference   <- data[ Date %in% 1850:2100, .(avg = mean(percent_change, na.rm = TRUE)), by = variable]
  trivial_threshold <- 0.5 # the average percent difference should be less than half of a percent different.
  testthat::expect_true(all(abs(mean_difference$avg) < trivial_threshold))
  
  # Note that the input tables generated by the hectordata & the older input tables is that 
  # the input tables also include values for the constraints & NH3 emissions. So all of the 
  # NA values in the comparison data frame should correspond to a constraint entry or the NH3 emissions.
  no_old_values <- unique(comparison_df[is.na(old_value) & Date == 2000,][["variable"]])
  # older version of Hector did not combine the RF, concentration constrains into the a single csv file, 
  # additional emission species were added so we would expect those to be in the new rcp file. 
  # A typo in hector < 3.0 also meant that we would expect those to show up in the no old values file. 
  expected_pattern <- "_constrain|NH3_emissions|SV|daccs_uptake|luc_uptake|Ftalbedo|HCFC141b_emissions|HCFC141b_emissions|HCFC22_emissions|HCFC142b_emissions"
  testthat::expect_true(all(grepl(pattern = expected_pattern, x = no_old_values)))

  
})